
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author komal dewnani
 */
public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jRadioButton8 = new javax.swing.JRadioButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("APPLY ONLINE");

        jLabel2.setText("SELECT BRANCH");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COMPUTER ENGG", "ELECTRONICS AND TELECOM", "INFORMATION TECH", "MECHANICAL ENGG", "AEROSPACE ENGINEERING", " ", " " }));

        jLabel3.setText("SELECT COURSES");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("B.Tech");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("B.Sc");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("B.Tech(Hons)");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("M.Sc");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("M.Tech");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("Ph.D");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jLabel4.setText("NAME");

        jTextField1.setBorder(null);

        jLabel5.setText("FATHER'S/HUSBAND'S NAME");

        jLabel6.setText("D.O.B.");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel7.setText("ADDRESS");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel8.setText("TUITION FEE");

        jTextField5.setEditable(false);

        jLabel9.setText("HOSTEL");

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("YES");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jLabel10.setText("TOTAL FEES ");

        jButton1.setText("FEE STRUCTURE");
        jButton1.setToolTipText("CLICK TO SEE THE FEE STRUCTURE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.setBorder(null);

        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setText("GENDER");

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText("NO");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jTextField7.setEditable(false);

        jButton4.setText("REQUIRED ELIGIBILITY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("SAVE DATA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setText("MALE");

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setText("FEMALE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton6)))
                                .addContainerGap(123, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                                        .addComponent(jTextField2))
                                                    .addComponent(jRadioButton8)
                                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(jButton1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jButton4)
                                                .addGap(29, 29, 29)))))
                                .addGap(22, 22, 22))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButton10)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(99, 99, 99))))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(107, 107, 107)
                        .addComponent(jRadioButton7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96)
                .addComponent(jButton3)
                .addGap(177, 177, 177))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(200, 200, 200)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(99, 99, 99)
                                .addComponent(jRadioButton9)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton4)
                        .addComponent(jRadioButton6)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jRadioButton7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jButton1)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
jLabel11.setVisible(true);  
jLabel12.setVisible(true);
jTextField8.setVisible(true);
jTextField7.setEditable(true);
jTextField8.setEditable(true);
jLabel11.setText("RANK(JEE MAINS)");
jLabel12.setText("RANK(JEE ADVANCED)");
jTextField5.setText("840000");
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
       
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
      
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
jLabel11.setVisible(true);  
jLabel12.setVisible(true);
jTextField8.setVisible(true);
jTextField7.setEditable(true);
jTextField8.setEditable(true);
jLabel11.setText("RANK(JEE MAINS)");
jLabel12.setText("RANK(JEE ADVANCED)");
jTextField5.setText("860000");        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
     jLabel11.setVisible(true);  
jLabel12.setVisible(false);
jTextField8.setVisible(false);
jTextField7.setEditable(true);
jTextField8.setEditable(false);
jLabel11.setText("AVERAGE % IN BTech");
jTextField5.setText("400000");   

    
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
jLabel11.setVisible(true);  
jLabel12.setVisible(true);
jTextField8.setVisible(true);
jTextField7.setEditable(true);
jTextField8.setEditable(true);
jLabel11.setText("RANK(JEE MAINS)");
jLabel12.setText("RANK(JEE ADVANCED)");
jTextField5.setText("840000"); 
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
       jLabel11.setVisible(true);  
jLabel12.setVisible(false);
jTextField8.setVisible(false);
jTextField7.setEditable(true);
jTextField8.setEditable(false);
jLabel11.setText("AVERAGE % IN BSc");
jTextField5.setText("400000");    // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
       jLabel11.setVisible(true);  
jLabel12.setVisible(false);
jTextField8.setVisible(false);
jTextField7.setEditable(true);
jTextField8.setEditable(false);
jLabel11.setText("AVERAGE % IN MSc/MTech");
jTextField5.setText("500000");// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int a,b;
a=Integer.parseInt(jTextField7.getText());
b=Integer.parseInt(jTextField8.getText());
if(jComboBox1.getSelectedIndex()==0)
{if(jRadioButton1.isSelected() )
{if(a>500 && b>1000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");

    
else
   
    {new NewJFrame5().setVisible(true);
dispose();}
 if(jRadioButton2.isSelected() )
{if(a>500 && b>1000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");
   else
   
    {new NewJFrame5().setVisible(true);
dispose(); }
 if(jRadioButton3.isSelected() )
{if(a>500 && b>1000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
 if(jRadioButton4.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
 if(jRadioButton5.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
 if(jRadioButton6.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}

    
}
else if(jComboBox1.getSelectedIndex()==1)
    {if(jRadioButton1.isSelected() )
{if(a>5000 && b>10000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");
else
   
    {new NewJFrame5().setVisible(true);
dispose();
    }
if(jRadioButton2.isSelected() )
{if(a>5000 && b>15000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");
   else
   
    {new NewJFrame5().setVisible(true);
dispose(); }
if(jRadioButton3.isSelected() )
{if(a>5000 && b>15000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton4.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton5.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton6.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
}
else if(jComboBox1.getSelectedIndex()==2)
     {if(jRadioButton1.isSelected() )
{if(a>15000 && b>25000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");
else
   
    {new NewJFrame5().setVisible(true);
dispose();
    }
if(jRadioButton2.isSelected() )
{if(a>15000 && b>25000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");
   else
   
    {new NewJFrame5().setVisible(true);
dispose(); }
if(jRadioButton3.isSelected() )
{if(a>15000 && b>25000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton4.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton5.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton6.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
}
else if(jComboBox1.getSelectedIndex()==3)
     {if(jRadioButton1.isSelected() )
{if(a>15000 && b>25000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");
else
   
    {new NewJFrame5().setVisible(true);
dispose();
    }
if(jRadioButton2.isSelected() )
{if(a>15000 && b>25000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");
 else
   
    {new NewJFrame5().setVisible(true);
dispose();   }
if(jRadioButton3.isSelected() )
{if(a>15000 && b>25000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton4.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton5.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton6.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
}
    else if(jComboBox1.getSelectedIndex()==4)
     {if(jRadioButton1.isSelected() )
{if(a>7000 && b>4000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");
else
   
    {new NewJFrame5().setVisible(true);
dispose();
    }
if(jRadioButton2.isSelected() )
{if(a>7000 && b>4000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");
  else
   
    {new NewJFrame5().setVisible(true);
dispose();  }
if(jRadioButton3.isSelected() )
{if(a>7000 && b>4000)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton4.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton5.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");else
   
    {new NewJFrame5().setVisible(true);
dispose();}
if(jRadioButton6.isSelected() )
{if(a<50)
    JOptionPane.showMessageDialog(this,"YOU ARE NOT ELIGIBLE");
else
   
    {new NewJFrame5().setVisible(true);
dispose();}
     }
    }}}}}}}}}}}}}}}}}}}}}}}}}}}}}}// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
int a,b;
a=Integer.parseInt(jTextField5.getText());
b=a+100000;
jTextField9.setText(Integer.toString(b));   

    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
 int a,b;
a=Integer.parseInt(jTextField5.getText());
b=a;
jTextField9.setText(Integer.toString(b));       // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new NewJFrame4().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
new NewJFrame6().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new NewJFrame11().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String course = null;
{if(jRadioButton1.isSelected())
    course="btech";
else if(jRadioButton2.isSelected())
course="bsc"; 
else if(jRadioButton3.isSelected())
course="btech(hons)"; 
else if(jRadioButton4.isSelected())
course="msc"; 
else if(jRadioButton5.isSelected())
course="mtech"; 
else if(jRadioButton6.isSelected())
{course="phd";}}
String name=jTextField1.getText();
String fname=jTextField2.getText();
String dob=jTextField3.getText();
String gender;
{if(jRadioButton9.isSelected())
gender="male";
else 
gender="female";}
String address=jTextField4.getText();
String tuitionfee=jTextField5.getText();
String hostel;
{if(jRadioButton7.isSelected())
    hostel="yes";
else
    hostel="no";
}
String totalfees=jTextField9.getText();
String rankmain=jTextField7.getText();
String bsc=jTextField7.getText();
String msc=jTextField7.getText();
String rankad=jTextField8.getText();
try
{Class.forName("java.sql.DriverManager");
Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/KOMALDEWNANI_10_12C","root","abc123");
Statement stmt=(Statement)con.createStatement();
String query;
if((jRadioButton1.isSelected())||(jRadioButton2.isSelected())||(jRadioButton3.isSelected()))
    query="INSERT INTO STUDENT VALUES('"+course+"','"+name+"','"+fname+"','"+dob+"','"+gender+"','"+address+"','"+tuitionfee+"','"+hostel+"','"+totalfees+"','"+rankmain+"','"+rankad+"');";
else if((jRadioButton4.isSelected())||(jRadioButton5.isSelected()))
    query="INSERT INTO STUDENT1 VALUES('"+course+"','"+name+"','"+fname+"','"+dob+"','"+gender+"','"+address+"','"+tuitionfee+"','"+hostel+"','"+totalfees+"','"+bsc+"');";
else
  query="INSERT INTO STUDENT2 VALUES('"+course+"','"+name+"','"+fname+"','"+dob+"','"+gender+"','"+address+"','"+tuitionfee+"','"+hostel+"','"+totalfees+"','"+msc+"');";  
stmt.executeUpdate(query);}
catch(Exception e)
{JOptionPane.showMessageDialog(this,e.getMessage());

}


// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
